db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=EPex62LGtwMAgkf2

wordpress:
  image: wordpress
  links:
      - db:mysql
  environment:
      - VIRTUAL_HOST=insonorizate.dev,insonorizate.com,miqueladell.dev
      - WORDPRESS_DB_PASSWORD=EPex62LGtwMAgkf2
      - WORDPRESS_DB_NAME=insonorizate
  ports:
       - "80"
  working_dir: /var/www/html
  volumes:
      - $PWD:/var/www/html/wp-content
